### ISSUE TITLE
Question: Is it possible to use React hooks with elmish-hooks

### ISSUE THREAD

**Issue by sigma-andex** [collegevine/purescript-elmish-hooks#17]
Is it possible to use an existing react hook with elmish-hooks?

I would like to use the `useAuth0` hook from [Auth0](https://github.com/auth0/auth0-react#getting-started), but I struggled creating an FFI for it from the examples.

**Comment by fsoikin** [comment]
No, it is not. At least not easily.

Elmish hooks are not based on React hooks, they're a completely different implementation, which just happens to have a vaguely similar API.

**Comment by sigma-andex** [comment]
Ok I see, thx for the quick answer! Will have to use the component wrapping then..
